digite = input('Digite algo: ')
print(type(digite))
print('Só tem espaços?', digite.isspace())
print('É um número?', digite.isnumeric())
print('É alfabético', digite.isalpha())
print("é alfanumérico", digite.isalnum())
print("Está em letras maiúsculas?", digite.isupper())
print("Está em letras minúsculas?", digite.islower())
print("Está capitalizada?", digite.istitle())
